### PR TITLE
Make library Python 2 and 3 compatible

### PR DESCRIPTION
**Pull request by timheap**
Some notes on how and why things were converted or fixed:
- `absolute_import`, `print_function`, `unicode_literals` are all imported so both versions function the same. These are imported in all `.py` files. This uncovered a number of bugs where bytes were required, but strings supplied. These bugs were hidden by Python2 defaulting to bytes.
- files opened with `"wb"` must write bytes out, and those opened with `"w"` must write strings.
- `file`s are iterable, no need for `xreadlines`
- `pyrax/object_storage.py`, line 1899: Comparing None with an int is a TypeError. fsize is only None when the filesize is unknown. If the filesize is unknown, proper chunking is not possible, so the file is uploaded as is. This matches the previous behaviour, as in Python2 `None < 1.0`.
- `next(iter)` instead of `iter.next()`
- `dict.keys()` returns an iterable, instead of a list, so indexing and `random.choice` no longer work.
- `os.path.walk()` has been changed to `os.walk()`, and functions rewritten to handle this

### CODE REVIEW

**Comment by timheap** [comment]
Annoyingly, the `tox.ini` changes were not picked up by TravisCI, so it did not run the Python 3 environment.

**Comment by EdLeafe** [comment]
You need to update the .travis.yml file for Travis to change its behavior.

**Comment by timheap** [comment]
I have updated the `.travis.yml` file now. All tests are passing in CPython 2.7, 3.4, and pypy

**Comment by briancurtin** [comment]
@timheap thanks a lot for your contribution! Since this is a very major change, we need to have a conversation on the Rackspace end of things how to manage this in terms of a release that would include it. I will offer some initial thoughts, though.

1. This is too large of a change to review all at once, so regardless of what we end up deciding when it comes to a release, this change should be broken up into smaller pieces.
2. One of my first concerns was a lot of importing of `print_function` and `unicode_literals` with no other changes to the file. `print_function` isn't necessary at all as we don't use print anywhere except for two places which already import `print_function`. The `unicode_literals` usage also requires a lot of delicate care, as we still have to evaluate str/bytes behavior throughout the entire file to ensure it's the right approach. Those may very well turn out to be correct uses of that import, but off the top of my head that wasn't the route I would have taken.
3. Have you tested this change with any tools or applications being used on a day-to-day basis with both Python 2 and Python 3? My initial thought is that we may want to keep this in its own branch while we ensure it gets some mileage. Ansible is perhaps the largest consumer of pyrax, so we need to ensure it continues functioning without a hitch.

As someone who once flew to Russia to advocate for Python 3 and have completed several ports of my own, I'm very much in favor of seeing an effort like this. I just want to make sure we do it right.

**Comment by timheap** [comment]
Thanks for the response, @briancurtin. To address your points:

1. I am happy to split it up, although I am not sure how best to do this. There are a number of small sets of changes that could be split up in to separate pull requests, such as fixing iterators, the `os.walk` changes, and using more things from `six`, for example. Would this work for you?

2. I added the `__future__` imports to the whole project to make the code behave consistently across all versions of Python. While adding it to every file is a large change, it will prevent future headaches when developer try to work out why code works differently depending upon which file it is in.

    Importing `print_function` is unnecessary in that there are very limited numbers of `print` statements, as you point out. However, without this change, if a developer comes along and tries to debug things by sticking `print` statements everywhere, they will have to be conscious of which file they are working in, and therefore which style of syntax to use.

    A similar argument can be made for `absolute_imports`: the old, Python 2 style relative import is both confusing, and invalid in Python 3, so forcing developers to use absolute imports or new style relative imports ensures that code will be compatible. 

    The `unicode_literals` change is quite large and scary, I agree, and I was hesitant to include it. My rationale was the sheer number of potential bugs it uncovered by adding it in. Byte strings and unicode strings are very different things. Most of the changes to strings happened because one form was being used where the other form was expected, but Python 2 was being forgiving and not enforcing correctness. By enabling `unicode_literals` in all files, these bugs can't hide as easily. I am happy to take your guidance on this change though, as it is the largest and most likely to cause subtle bugs.

3. I have not tested this with any tools yet. I am developing an application in Python 3, and we want to use Rackspace for some of our functionality. I have not had a chance to use this package yet, as I had to make it work in Python 3 before I could test it! Keeping this in its own branch until it gets some real world testing is sensible.

**Comment by briancurtin** [comment]
1. When I ported parts of Ubuntu One to Python 3, I did it how you mentioned - one submission per type of change, which worked pretty well. I've also just turned one big change into four smaller ones pretty much arbitrarily.
2. On the print function - if people are adding prints they need to manage that on their own. On the rest, I'll have to dig in and look further before having a solid answer.
3. Would you mind emailing me at brian dot curtin at rackspace? I'd love to find out what you're working on if possible and see how we can help you get what you need. We're in the process of building out a new SDK that will at some point replace pyrax, but we haven't set a roadmap for how the two will proceed. That's actually something I'm working out right now.

**Comment by timheap** [comment]
I'll integrate your feedback when I am back at work on Monday.

**Comment by timheap** [comment]
This pull request is now just a merge of all the other Python 3 pull requests I have just submitted, namely: #529, #530, #531, #532, #533, #534, #535, and #536

**Comment by drewbrew** [comment]
Since the updated versions of the split PRs have all been merged into master, I'm closing this PR. Thanks again for submitting this!

**Pull request closed without merging**
